# Generated by Django 3.2.16 on 2022-11-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='descrptn',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='name1',
        ),
    ]
